In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import euclidean_distances

In [2]:
PROJECT_ROOT = Path.cwd().parent

FEATURES_PATH = (
    PROJECT_ROOT /
    "outputs" /
    "natural_sound_features.csv"
)

features_df = pd.read_csv(FEATURES_PATH)

print(features_df.shape)

features_df.head()

(520, 14)

,mean,std,min,max,skewness,kurtosis,rms,entropy,zcr,spectral_centroid,spectral_bandwidth,spectral_rolloff,filename,category
0,-0.000001,0.061434,-0.480499,0.545563,0.392988,10.404342,0.061434,2.948086,0.157994,4042.281204,2643.109696,6623.483383,1-100038-A-14.wav,chirping_birds
1,-0.000003,0.010946,-0.082306,0.102997,0.157899,8.572530,0.010946,3.013087,0.027574,2075.738865,3455.603120,4559.843116,1-101296-A-19.wav,thunderstorm
2,-0.000010,0.016860,-0.164459,0.156952,-0.039740,10.883121,0.016860,2.866590,0.028877,1850.646524,3093.555844,3547.033153,1-101296-B-19.wav,thunderstorm
3,-0.000253,0.136177,-0.945587,0.999969,0.027326,2.776779,0.136177,3.313940,0.041329,2675.116865,3530.183905,6261.615656,1-103298-A-9.wav,crow
4,-0.000025,0.063967,-0.816681,0.980133,-0.052734,29.311878,0.063967,2.170481,0.010723,446.951318,1005.672928,696.156966,1-115521-A-19.wav,thunderstorm

In [3]:
feature_columns = [

    "mean",
    "std",
    "min",
    "max",

    "skewness",
    "kurtosis",

    "rms",

    "entropy",

    "zcr",

    "spectral_centroid",
    "spectral_bandwidth",
    "spectral_rolloff"

]

X = features_df[feature_columns]

print(X.shape)

(520, 12)

In [4]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print(X_scaled.shape)

(520, 12)

In [5]:
distance_matrix = euclidean_distances(X_scaled)

print(distance_matrix.shape)

(520, 520)

In [6]:
distance_matrix[:5, :5]

array([[0.        , 2.94798083, 2.77820633, 3.06799741, 3.79022016],
       [2.94798083, 0.        , 0.56197604, 4.68227504, 4.57913313],
       [2.77820633, 0.56197604, 0.        , 4.4360222 , 4.08258904],
       [3.06799741, 4.68227504, 4.4360222 , 0.        , 3.32494732],
       [3.79022016, 4.57913313, 4.08258904, 3.32494732, 0.        ]])

In [7]:
def find_similar_sounds(index, top_n=5):

    distances = distance_matrix[index]

    nearest_indices = np.argsort(distances)

    nearest_indices = nearest_indices[1:top_n+1]

    results = features_df.iloc[
        nearest_indices
    ][["filename", "category"]]

    return results

In [8]:
find_similar_sounds(0)

              filename        category
367   4-173865-B-9.wav            crow
39    1-29561-A-10.wav            rain
25    1-21189-A-10.wav            rain
509  5-243459-A-14.wav  chirping_birds
510  5-243459-B-14.wav  chirping_birds

In [9]:
features_df.iloc[0][
    ["filename", "category"]
]

filename    1-100038-A-14.wav
category       chirping_birds
Name: 0, dtype: object

In [10]:
query_sound = features_df.iloc[0]

print("QUERY SOUND")
print(query_sound["filename"])
print(query_sound["category"])

print("\nMOST SIMILAR SOUNDS")

find_similar_sounds(0)

QUERY SOUND
1-100038-A-14.wav
chirping_birds

MOST SIMILAR SOUNDS

              filename        category
367   4-173865-B-9.wav            crow
39    1-29561-A-10.wav            rain
25    1-21189-A-10.wav            rain
509  5-243459-A-14.wav  chirping_birds
510  5-243459-B-14.wav  chirping_birds